import 'package:flutter/foundation.dart';

/// AmplifyService — stubbed until 'npx ampx sandbox' generates amplify_outputs.dart
/// Once the sandbox has deployed:
///   1. Uncomment the amplify imports at the top
///   2. Uncomment the configure call in configureAmplify()
///   3. Remove the mock implementations below
class AmplifyService {
  static final AmplifyService _instance = AmplifyService._internal();
  factory AmplifyService() => _instance;
  AmplifyService._internal();

  Future<void> configureAmplify() async {
    // TODO: Uncomment once amplify_outputs.dart is generated by 'npx ampx sandbox'
    // import 'package:amplify_auth_cognito/amplify_auth_cognito.dart';
    // import 'package:amplify_flutter/amplify_flutter.dart';
    // import 'package:amplify_api/amplify_api.dart';
    // import 'package:amplify_storage_s3/amplify_storage_s3.dart';
    // import 'amplify_outputs.dart';
    //
    // if (!Amplify.isConfigured) {
    //   await Amplify.addPlugins([
    //     AmplifyAuthCognito(),
    //     AmplifyAPI(),
    //     AmplifyStorageS3(),
    //   ]);
    //   await Amplify.configure(amplifyConfig);
    // }
    debugPrint('AmplifyService: Running in stub mode. Backend not yet configured.');
  }

  // ── Auth Methods ──────────────────────────────────────────────────────────

  /// Mock sign-in — returns true for any non-empty credentials while backend is not live.
  Future<bool> signIn(String email, String password) async {
    debugPrint('AmplifyService: Mock signIn called for $email');
    await Future.delayed(const Duration(milliseconds: 500));
    return email.isNotEmpty && password.isNotEmpty;
  }

  Future<void> signOut() async {
    debugPrint('AmplifyService: Mock signOut called');
  }

  // ── API / Database Methods ────────────────────────────────────────────────

  Future<void> createUser(Map<String, dynamic> userData) async {
    debugPrint('AmplifyService: Mock createUser called with $userData');
  }

  Future<void> sendMessage(String pairingId, String content, String type) async {
    debugPrint('AmplifyService: Mock sendMessage → $pairingId: $content');
  }

  // ── Storage Methods ───────────────────────────────────────────────────────

  Future<String?> uploadFile(String filePath, String name) async {
    debugPrint('AmplifyService: Mock uploadFile called for $name');
    return 'mock-url/uploads/$name';
  }
}
